stores:
  rewe:
    name: "REWE"
    enabled: true
    api_type: "marktguru"
  
  lidl:
    name: "Lidl"
    enabled: true
    api_type: "marktguru"
  
  aldi-sued:
    name: "Aldi Süd"
    enabled: true
    api_type: "marktguru"
  
  kaufland:
    name: "Kaufland"
    enabled: true
    api_type: "marktguru"
